version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    networks:
      - demo-network
    depends_on:
      - localstack
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=xyx
      - AWS_SESSION_TOKEN=abc
      - S3_BUCKET_NAME=demo
      - S3_FILE_KEY_DEFAULT_TEMPLATE=standard.html
  
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    networks:
     - demo-network
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  demo-network: